USE UNIVERSIDAD
GO

CREATE TRIGGER [T_ID_Facultad]
ON [dbo].[FACULTAD]
INSTEAD OF DELETE
AS
BEGIN
	SET NOCOUNT ON
	UPDATE dbo.FACULTAD SET estado = 1
	FROM dbo.FACULTAD f
	INNER JOIN deleted i 
	ON f.id = i.id
END
